spring.application.name=watchwise-backend
server.port=8080

# PostgreSQL (Neon)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=${JWT_SECRET}
jwt.access.expiration=86400000
