

spring.application.name=watchwise-backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/usevcube?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=WatchWiseSuperSecretKey1234567890ABCDEF
jwt.access.expiration=86400000

SENDGRID_API_KEY=SG.your_key_here
